# Generated by Django 4.2.7 on 2023-12-03 00:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('audio_library', '0002_alter_track_user_of_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='user_of_likes',
            field=models.ManyToManyField(blank=True, related_name='likes_of_tracks', to=settings.AUTH_USER_MODEL),
        ),
    ]
