# Generated by Django 4.2.7 on 2023-12-08 18:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_library', '0004_playedusertrack'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playedusertrack',
            name='played_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 8, 20, 20, 41, 327619)),
        ),
    ]
