# Generated by Django 4.2.7 on 2023-12-08 18:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_library', '0005_alter_playedusertrack_played_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playedusertrack',
            name='played_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 8, 18, 27, 13, 497380, tzinfo=datetime.timezone.utc)),
        ),
    ]
