version: '3.11'


services:
    nginx:
        restart: always
        image: nginx:1.25-alpine
        ports:
            - "80:80"
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - static_volume:/app/clone_sound_cloud/django_static
    server:
        restart: unless-stopped
        build:
            context: .
            dockerfile: ./docker/backend/Dockerfile
        entrypoint: /app/docker/backend/server-entrypoint.sh
        volumes:
            - static_volume:/app/clone_sound_cloud/django_static
        expose:
            - "8000:8000"
        env_file:
            - .env.docker
    worker:
        restart: unless-stopped
        build:
            context: .
            dockerfile: ./docker/backend/Dockerfile
        entrypoint: /app/docker/backend/worker-entrypoint.sh
        volumes:
            - static_volume:/app/clone_sound_cloud/django_static
        env_file:
            - .env.docker
        depends_on:
            - server
            - redis
    celery-beat:
        restart: unless-stopped
        build:
            context: .
            dockerfile: ./docker/backend/Dockerfile
        entrypoint: /app/docker/backend/celery-beat-entrypoint.sh
        volumes:
            - static_volume:/app/clone_sound_cloud/django_static
        env_file:
            - .env.docker
        depends_on:
            - server
            - redis
            - worker
    redis:
        restart: unless-stopped
        image: redis:7.0.5-alpine
        sysctls:
            net.core.somaxconn: "4096"
        expose:
            - "6379"
    db:
        image: postgres:15.0-alpine
        restart: unless-stopped
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        env_file:
            - .env.docker
        expose:
            - "5432"

volumes:
    static_volume: {}
    postgres_data: {}