# Generated by Django 4.2.7 on 2023-12-16 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0002_spamemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_spam_email',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='SpamEmail',
        ),
    ]
