name: GitHub Actions Django
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run_unittests:
    runs-on: ubuntu-latest
    environment: Clone-sound-cloud-env
    strategy:
      max-parallel: 4
      matrix:
        python-version: ['3.11']
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Tests
        run: |
          cd ./clone_sound_cloud
          python manage.py test
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          DJANGO_DB: ${{ secrets.DJANGO_DB }}
          EMAIL_HOST: ${{ secrets.EMAIL_HOST }}
          EMAIL_PORT: ${{ secrets.EMAIL_PORT }}
          EMAIL_HOST_USER: ${{ secrets.EMAIL_HOST_USER }}
          EMAIL_HOST_PASSWORD: ${{ secrets.EMAIL_HOST_PASSWORD }}
          SOCIAL_AUTH_SPOTIFY_KEY: ${{ secrets.SOCIAL_AUTH_SPOTIFY_KEY }}
          SOCIAL_AUTH_SPOTIFY_SECRET: ${{ secrets.SOCIAL_AUTH_SPOTIFY_SECRET }}
          SOCIAL_AUTH_GOOGLE_OAUTH2_KEY: ${{ secrets.SOCIAL_AUTH_GOOGLE_OAUTH2_KEY }}
          SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET: ${{ secrets.SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET }}
      - name: Run Linting
        run: |
          cd ./clone_sound_cloud
          python -m flake8